---

- name: Ensure dpkg lists file is removed
  file:
    state: absent
    path: "/var/lib/apt/lists/lock"

- name: Ensure dpkg lock file is removed
  file:
    state: absent
    path: "/var/lib/dpkg/lock"

- name: Ensure apt-transport-https is installed.
  apt: name=apt-transport-https state=present

-



- name: Add Nodesource apt key.
  apt_key:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280
    id: "68576280"
    state: present

- debug:
    msg: "show ansible ddistibution  {{ ansible_distribution_release }}"

- debug:
    msg: "show ansible nodejs_version  {{nodejs_version }}"

- name: Add NodeSource repositories for Node.js.
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "deb https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"
    - "deb-src https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"
  register: node_repo

- name: Update apt cache if repo was added.
  apt: update_cache=yes
  when: node_repo.changed

- name: Ensure Node.js and npm are installed.
  apt: "name=nodejs={{ nodejs_version|regex_replace('x', '') }}* state=present"
